### ISSUE TITLE
Use request

### ISSUE THREAD

**Issue by codixor** [phpgearbox/router#1]
Hello,

Very cool code and thank you 

How  to use Request function for Route::filter method ?

**Comment by brad-jones** [comment]
I must admit I have not yet tried to use Route::filter with this package but theoretically it should work.
I need to write a heap more unit tests...

Please keep in mind all this project does is provides the Route API.
It does not expose any of the other Laravel helpers such as Request, Input, Redirect, etc.

Once the router has decided which route is going to run you would then need to use traditional PHP code such as $_GET & $_POST instead of Input:: or $_SERVER['REQUEST_URI'] instead of Request::path().

I have thought about implementing these extra Helpers however at what point do you stop.
You may as well just use Laravel.

Hopefully that makes sense.

**Comment by codixor** [comment]
I test and Work fine for Route::filter,

but to adjuste filters with requests like ajax,

need to return the request instance from Router class 

``` php
 $this->request = function()
{
    return Request::createFromGlobals();
};
```

**Comment by brad-jones** [comment]
Its a bit hacky but it might work for you.
Just create a new instance inside your filter, for example:

``` php
Route::filter('example', function()
{
    $request_instance = Illuminate\Http\Request::createFromGlobals();
});
```

I am not entirely sure what you are trying to achieve. Perhaps post up some example code.
Or better yet send a pull request through with the changes you want.

**Comment by codixor** [comment]
I make this changes in Router class

I returnd the request instance from the class

``` php
public function dispatch()
{
       return $this->install();
}

public function request()
{
    return $this->request;
}
```

Now I can use it like this::

``` php
Route::filter('csrf', function()
{
    if (Session::token() !== Route::request()->get('_token'))
    {
        return new Response(['success' => false, 'message' => 'Invalid Token']);
    }
});
```
